autoDetectedPackages:
- com.xunqi.common.constant
- com.xunqi.common.es
- com.xunqi.common.exception
- com.xunqi.common.to
- com.xunqi.common.utils
- com.xunqi.common.valid
- com.xunqi.common.vo
- com.xunqi.common.xss
- com.xunqi.gulimall.auth
- com.xunqi.gulimall.cart
- com.xunqi.gulimall.coupon
- com.xunqi.gulimall.gateway
- com.xunqi.gulimall.gulimallware
- com.xunqi.gulimall.member
- com.xunqi.gulimall.order
- com.xunqi.gulimall.product
- com.xunqi.gulimall.search
- com.xunqi.gulimall.seckill
- com.xunqi.gulimall.ssoclient
- com.xunqi.gulimall.ssoserver
- com.xunqi.gulimall.thirdparty
- com.xunqi.gulimall.ware
- io.renren
enableAutoDetect: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
